// Code generated by command: go run addconst_asm.go -bits 32 -out ../../asm/asm32/addconst_amd64.s -stubs ../../asm/asm32/addconst_amd64.go -pkg asm32. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm32

// AddConstAVX adds a constant value c to each element of x, storing the result in y (32 bits, AVX required).
//
//go:noescape
func AddConstAVX(c float32, x []float32, y []float32)

// AddConstSSE adds a constant value c to each element of x, storing the result in y (32 bits, SSE required).
//
//go:noescape
func AddConstSSE(c float32, x []float32, y []float32)
