// Code generated by command: go run dotprod_asm.go -bits 32 -out ../../asm/asm32/dotprod_amd64.s -stubs ../../asm/asm32/dotprod_amd64.go -pkg asm32. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm32

// DotProdAVX returns the dot product between x1 and x2 (32 bits, AVX required).
//
//go:noescape
func DotProdAVX(x1 []float32, x2 []float32) float32

// DotProdSSE returns the dot product between x1 and x2 (32 bits, SSE required).
//
//go:noescape
func DotProdSSE(x1 []float32, x2 []float32) float32
