// Code generated by command: go run exp_asm.go -bits 32 -out ../../asm/asm32/exp_amd64.s -stubs ../../asm/asm32/exp_amd64.go -pkg asm32. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm32

// ExpAVX computes the base-e exponential of each element of x, storing the result in y (32 bits, AVX required).
//
//go:noescape
func ExpAVX(x []float32, y []float32)

// ExpSSE computes the base-e exponential of each element of x, storing the result in y (32 bits, SSE required).
//
//go:noescape
func ExpSSE(x []float32, y []float32)
