// Code generated by command: go run log_asm.go -bits 32 -out ../../asm/asm32/log_amd64.s -stubs ../../asm/asm32/log_amd64.go -pkg asm32. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm32

// LogAVX computes the natural logarithm of each element of x, storing the result in y (32 bits, AVX2 required).
//
//go:noescape
func LogAVX(x []float32, y []float32)

// LogSSE computes the natural logarithm of each element of x, storing the result in y (32 bits, SSE required).
//
//go:noescape
func LogSSE(x []float32, y []float32)
