// Code generated by command: go run sum_asm.go -bits 32 -out ../../asm/asm32/sum_amd64.s -stubs ../../asm/asm32/sum_amd64.go -pkg asm32. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm32

// SumAVX returns the sum of all values of x (32 bits, AVX required).
//
//go:noescape
func SumAVX(x []float32) float32

// SumSSE returns the sum of all values of x (32 bits, SSE required).
//
//go:noescape
func SumSSE(x []float32) float32
