// Copyright 2015 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package lapack

// Panic strings used during parameter checks.
// This list is duplicated in netlib/lapack/netlib. Keep in sync.
const (
	// Vector increment errors
	ErrZeroIncV     = "lapack: incv == 0"
	ErrBadIncX      = "lapack: incX <= 0"
	ErrBadIncY      = "lapack: incY <= 0"
	ErrAbsIncNotOne = "lapack: increment not one or negative one"

	// Dimension errors
	ErrMLT0  = "lapack: m < 0"
	ErrNLT0  = "lapack: n < 0"
	ErrKLT0  = "lapack: k < 0"
	ErrKLT1  = "lapack: k < 1"
	ErrKdLT0 = "lapack: kd < 0"
	ErrKlLT0 = "lapack: kl < 0"
	ErrKuLT0 = "lapack: ku < 0"
	ErrPLT0  = "lapack: p < 0"

	// Dimension relationship errors
	ErrKGTM = "lapack: k > m"
	ErrKGTN = "lapack: k > n"
	ErrMGTN = "lapack: m > n"
	ErrNGTM = "lapack: n > m"
	ErrNLTM = "lapack: n < m"

	// Leading dimension errors
	ErrBadLdA    = "lapack: bad leading dimension of A"
	ErrBadLdB    = "lapack: bad leading dimension of B"
	ErrBadLdC    = "lapack: bad leading dimension of C"
	ErrBadLdF    = "lapack: bad leading dimension of F"
	ErrBadLdH    = "lapack: bad leading dimension of H"
	ErrBadLdQ    = "lapack: bad leading dimension of Q"
	ErrBadLdT    = "lapack: bad leading dimension of T"
	ErrBadLdU    = "lapack: bad leading dimension of U"
	ErrBadLdV    = "lapack: bad leading dimension of V"
	ErrBadLdVL   = "lapack: bad leading dimension of VL"
	ErrBadLdVR   = "lapack: bad leading dimension of VR"
	ErrBadLdVT   = "lapack: bad leading dimension of VT"
	ErrBadLdW    = "lapack: bad leading dimension of W"
	ErrBadLdWH   = "lapack: bad leading dimension of WH"
	ErrBadLdWV   = "lapack: bad leading dimension of WV"
	ErrBadLdWork = "lapack: bad leading dimension of Work"
	ErrBadLdX    = "lapack: bad leading dimension of X"
	ErrBadLdY    = "lapack: bad leading dimension of Y"
	ErrBadLdZ    = "lapack: bad leading dimension of Z"

	// Insufficient slice length errors
	ErrShortA     = "lapack: insufficient length of a"
	ErrShortAB    = "lapack: insufficient length of ab"
	ErrShortAuxv  = "lapack: insufficient length of auxv"
	ErrShortB     = "lapack: insufficient length of b"
	ErrShortC     = "lapack: insufficient length of c"
	ErrShortCNorm = "lapack: insufficient length of cnorm"
	ErrShortD     = "lapack: insufficient length of d"
	ErrShortDL    = "lapack: insufficient length of dl"
	ErrShortDU    = "lapack: insufficient length of du"
	ErrShortE     = "lapack: insufficient length of e"
	ErrShortF     = "lapack: insufficient length of f"
	ErrShortH     = "lapack: insufficient length of h"
	ErrShortIWork = "lapack: insufficient length of iwork"
	ErrShortIsgn  = "lapack: insufficient length of isgn"
	ErrShortQ     = "lapack: insufficient length of q"
	ErrShortRHS   = "lapack: insufficient length of rhs"
	ErrShortS     = "lapack: insufficient length of s"
	ErrShortScale = "lapack: insufficient length of scale"
	ErrShortT     = "lapack: insufficient length of t"
	ErrShortTau   = "lapack: insufficient length of tau"
	ErrShortTauP  = "lapack: insufficient length of tauP"
	ErrShortTauQ  = "lapack: insufficient length of tauQ"
	ErrShortU     = "lapack: insufficient length of u"
	ErrShortV     = "lapack: insufficient length of v"
	ErrShortVL    = "lapack: insufficient length of vl"
	ErrShortVR    = "lapack: insufficient length of vr"
	ErrShortVT    = "lapack: insufficient length of vt"
	ErrShortVn1   = "lapack: insufficient length of vn1"
	ErrShortVn2   = "lapack: insufficient length of vn2"
	ErrShortW     = "lapack: insufficient length of w"
	ErrShortWH    = "lapack: insufficient length of wh"
	ErrShortWV    = "lapack: insufficient length of wv"
	ErrShortWi    = "lapack: insufficient length of wi"
	ErrShortWork  = "lapack: insufficient length of work"
	ErrShortWr    = "lapack: insufficient length of wr"
	ErrShortX     = "lapack: insufficient length of x"
	ErrShortY     = "lapack: insufficient length of y"
	ErrShortZ     = "lapack: insufficient length of z"

	// Bad enumeration values
	ErrBadApplyOrtho       = "lapack: bad ApplyOrtho"
	ErrBadBalanceJob       = "lapack: bad BalanceJob"
	ErrBadDiag             = "lapack: bad Diag"
	ErrBadDirect           = "lapack: bad Direct"
	ErrBadEVComp           = "lapack: bad EVComp"
	ErrBadEVHowMany        = "lapack: bad EVHowMany"
	ErrBadEVJob            = "lapack: bad EVJob"
	ErrBadEVSide           = "lapack: bad EVSide"
	ErrBadGSVDJob          = "lapack: bad GSVDJob"
	ErrBadGenOrtho         = "lapack: bad GenOrtho"
	ErrBadLeftEVJob        = "lapack: bad LeftEVJob"
	ErrBadMatrixType       = "lapack: bad MatrixType"
	ErrBadMaximizeNormXJob = "lapack: bad MaximizeNormXJob"
	ErrBadNorm             = "lapack: bad Norm"
	ErrBadOrthoComp        = "lapack: bad OrthoComp"
	ErrBadPivot            = "lapack: bad Pivot"
	ErrBadRightEVJob       = "lapack: bad RightEVJob"
	ErrBadSVDJob           = "lapack: bad SVDJob"
	ErrBadSchurComp        = "lapack: bad SchurComp"
	ErrBadSchurJob         = "lapack: bad SchurJob"
	ErrBadSide             = "lapack: bad Side"
	ErrBadSort             = "lapack: bad Sort"
	ErrBadStoreV           = "lapack: bad StoreV"
	ErrBadTrans            = "lapack: bad Trans"
	ErrBadUpdateSchurComp  = "lapack: bad UpdateSchurComp"
	ErrBadUplo             = "lapack: bad Uplo"

	// Specific parameter errors
	ErrBadLWork    = "lapack: insufficient declared workspace length"
	ErrBothSVDOver = "lapack: both jobU and jobVT are lapack.SVDOverwrite"
	ErrNotIsolated = "lapack: block is not isolated"
	ErrZeroCFrom   = "lapack: zero cfrom"
	ErrNanCFrom    = "lapack: cfrom is NaN"
	ErrNanCTo      = "lapack: cto is NaN"
	ErrNegANorm    = "lapack: anorm < 0"
	ErrNegZ        = "lapack: negative z value"

	// Range and value errors
	ErrBadName   = "lapack: bad name"
	ErrBadShifts = "lapack: bad shifts"
	ErrNshftsOdd = "lapack: nshfts must be even"
	ErrBadJpvt   = "lapack: bad element of jpvt"
	ErrBadIsave  = "lapack: bad isave value"
	ErrBadIspec  = "lapack: bad ispec value"
	ErrBadKacc22 = "lapack: invalid value of kacc22"

	// Index out of range errors (consolidated similar patterns)
	ErrIfstRange = "lapack: ifst out of range"
	ErrIhiRange  = "lapack: ihi out of range"
	ErrIhizRange = "lapack: ihiz out of range"
	ErrIloRange  = "lapack: ilo out of range"
	ErrIlozRange = "lapack: iloz out of range"
	ErrIlstRange = "lapack: ilst out of range"
	ErrJ1Range   = "lapack: j1 out of range"
	ErrK1Range   = "lapack: k1 out of range"
	ErrK2Range   = "lapack: k2 out of range"
	ErrKbotRange = "lapack: kbot out of range"
	ErrKtopRange = "lapack: ktop out of range"
	ErrMmRange   = "lapack: mm out of range"

	// Negative value errors (consolidated)
	ErrI0LT0     = "lapack: i0 < 0"
	ErrMmLT0     = "lapack: mm < 0"
	ErrN0LT0     = "lapack: n0 < 0"
	ErrNbLT0     = "lapack: nb < 0"
	ErrNccLT0    = "lapack: ncc < 0"
	ErrNcvtLT0   = "lapack: ncvt < 0"
	ErrNhLT0     = "lapack: nh < 0"
	ErrNrhsLT0   = "lapack: nrhs < 0"
	ErrNruLT0    = "lapack: nru < 0"
	ErrNshftsLT0 = "lapack: nshfts < 0"
	ErrNvLT0     = "lapack: nv < 0"
	ErrOffsetLT0 = "lapack: offset < 0"
	ErrRecurLT0  = "lapack: recur < 0"

	// Greater than errors (consolidated)
	ErrNbGTM     = "lapack: nb > m"
	ErrNbGTN     = "lapack: nb > n"
	ErrOffsetGTM = "lapack: offset > m"

	// Bad value errors (consolidated similar patterns)
	ErrBadN1 = "lapack: bad value of n1"
	ErrBadN2 = "lapack: bad value of n2"
	ErrBadNa = "lapack: bad value of na"
	ErrBadNh = "lapack: bad value of nh"
	ErrBadNw = "lapack: bad value of nw"
	ErrBadPp = "lapack: bad value of pp"

	// Bad slice length errors (consolidated)
	ErrBadLenAlpha    = "lapack: bad length of alpha"
	ErrBadLenBeta     = "lapack: bad length of beta"
	ErrBadLenIpiv     = "lapack: bad length of ipiv"
	ErrBadLenJpiv     = "lapack: bad length of jpiv"
	ErrBadLenJpvt     = "lapack: bad length of jpvt"
	ErrBadLenK        = "lapack: bad length of k"
	ErrBadLenPiv      = "lapack: bad length of piv"
	ErrBadLenSelected = "lapack: bad length of selected"
	ErrBadLenSi       = "lapack: bad length of si"
	ErrBadLenSr       = "lapack: bad length of sr"
	ErrBadLenTau      = "lapack: bad length of tau"
	ErrBadLenWi       = "lapack: bad length of wi"
	ErrBadLenWr       = "lapack: bad length of wr"
)
