// Code generated by command: go run add_asm.go -bits 32 -out ../../mat32/add_amd64.s -stubs ../../mat32/add_amd64.go -pkg mat32. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package mat32

// AddAVX adds x1 and x2 element-wise, storing the result in y (32 bits, AVX required).
//
//go:noescape
func AddAVX(x1 []float32, x2 []float32, y []float32)

// AddSSE adds x1 and x2 element-wise, storing the result in y (32 bits, SSE required).
//
//go:noescape
func AddSSE(x1 []float32, x2 []float32, y []float32)
