// Code generated by command: go run div_asm.go -bits 32 -out ../../mat32/div_amd64.s -stubs ../../mat32/div_amd64.go -pkg mat32. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package mat32

// DivAVX divides x1 by x2, element-wise, storing the result in y (32 bits, AVX required).
//
//go:noescape
func DivAVX(x1 []float32, x2 []float32, y []float32)

// DivSSE divides x1 by x2, element-wise, storing the result in y (32 bits, SSE required).
//
//go:noescape
func DivSSE(x1 []float32, x2 []float32, y []float32)
