// Code generated by command: go run mulconst_asm.go -bits 32 -out ../../mat32/mulconst_amd64.s -stubs ../../mat32/mulconst_amd64.go -pkg mat32. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package mat32

// MulConstAVX multiplies each element of x by a constant value c, storing the result in y (32 bits, AVX required).
//
//go:noescape
func MulConstAVX(c float32, x []float32, y []float32)

// MulConstSSE multiplies each element of x by a constant value c, storing the result in y (32 bits, SSE required).
//
//go:noescape
func MulConstSSE(c float32, x []float32, y []float32)
