// Code generated by command: go run sub_asm.go -bits 32 -out ../../mat32/sub_amd64.s -stubs ../../mat32/sub_amd64.go -pkg mat32. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package mat32

// SubAVX subtracts x2 from x1, element-wise, storing the result in y (32 bits, AVX required).
//
//go:noescape
func SubAVX(x1 []float32, x2 []float32, y []float32)

// SubSSE subtracts x2 from x1, element-wise, storing the result in y (32 bits, SSE required).
//
//go:noescape
func SubSSE(x1 []float32, x2 []float32, y []float32)
