// Code generated by command: go run sum_asm.go -bits 64 -out ../../mat/sum_amd64.s -stubs ../../mat/sum_amd64.go -pkg mat. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package mat

// SumAVX returns the sum of all values of x (64 bits, AVX required).
//
//go:noescape
func SumAVX(x []float64) float64

// SumSSE returns the sum of all values of x (64 bits, SSE required).
//
//go:noescape
func SumSSE(x []float64) float64
