// Code generated by command: go run add_asm.go -bits 64 -out ../../asm/asm64/add_amd64.s -stubs ../../asm/asm64/add_amd64.go -pkg asm64. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm64

// AddAVX adds x1 and x2 element-wise, storing the result in y (64 bits, AVX required).
//
//go:noescape
func AddAVX(x1 []float64, x2 []float64, y []float64)

// AddSSE adds x1 and x2 element-wise, storing the result in y (64 bits, SSE required).
//
//go:noescape
func AddSSE(x1 []float64, x2 []float64, y []float64)
