// Code generated by command: go run addconst_asm.go -bits 64 -out ../../asm/asm64/addconst_amd64.s -stubs ../../asm/asm64/addconst_amd64.go -pkg asm64. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm64

// AddConstAVX adds a constant value c to each element of x, storing the result in y (64 bits, AVX required).
//
//go:noescape
func AddConstAVX(c float64, x []float64, y []float64)

// AddConstSSE adds a constant value c to each element of x, storing the result in y (64 bits, SSE required).
//
//go:noescape
func AddConstSSE(c float64, x []float64, y []float64)
