// Code generated by command: go run div_asm.go -bits 64 -out ../../asm/asm64/div_amd64.s -stubs ../../asm/asm64/div_amd64.go -pkg asm64. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm64

// DivAVX divides x1 by x2, element-wise, storing the result in y (64 bits, AVX required).
//
//go:noescape
func DivAVX(x1 []float64, x2 []float64, y []float64)

// DivSSE divides x1 by x2, element-wise, storing the result in y (64 bits, SSE required).
//
//go:noescape
func DivSSE(x1 []float64, x2 []float64, y []float64)
