// Code generated by command: go run dotprod_asm.go -bits 64 -out ../../asm/asm64/dotprod_amd64.s -stubs ../../asm/asm64/dotprod_amd64.go -pkg asm64. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm64

// DotProdAVX returns the dot product between x1 and x2 (64 bits, AVX required).
//
//go:noescape
func DotProdAVX(x1 []float64, x2 []float64) float64

// DotProdSSE returns the dot product between x1 and x2 (64 bits, SSE required).
//
//go:noescape
func DotProdSSE(x1 []float64, x2 []float64) float64
