// Code generated by command: go run mulconst_asm.go -bits 64 -out ../../asm/asm64/mulconst_amd64.s -stubs ../../asm/asm64/mulconst_amd64.go -pkg asm64. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm64

// MulConstAVX multiplies each element of x by a constant value c, storing the result in y (64 bits, AVX required).
//
//go:noescape
func MulConstAVX(c float64, x []float64, y []float64)

// MulConstSSE multiplies each element of x by a constant value c, storing the result in y (64 bits, SSE required).
//
//go:noescape
func MulConstSSE(c float64, x []float64, y []float64)
