// Code generated by command: go run sub_asm.go -bits 64 -out ../../asm/asm64/sub_amd64.s -stubs ../../asm/asm64/sub_amd64.go -pkg asm64. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm64

// SubAVX subtracts x2 from x1, element-wise, storing the result in y (64 bits, AVX required).
//
//go:noescape
func SubAVX(x1 []float64, x2 []float64, y []float64)

// SubSSE subtracts x2 from x1, element-wise, storing the result in y (64 bits, SSE required).
//
//go:noescape
func SubSSE(x1 []float64, x2 []float64, y []float64)
