// Code generated by command: go run sum_asm.go -bits 64 -out ../../asm/asm64/sum_amd64.s -stubs ../../asm/asm64/sum_amd64.go -pkg asm64. DO NOT EDIT.

//go:build amd64 && gc && !noasm && !gccgo

package asm64

// SumAVX returns the sum of all values of x (64 bits, AVX required).
//
//go:noescape
func SumAVX(x []float64) float64

// SumSSE returns the sum of all values of x (64 bits, SSE required).
//
//go:noescape
func SumSSE(x []float64) float64
